apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: node
  namespace: production
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - hello-node
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
